# Generated by Django 6.0.5 on 2026-05-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_game_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='created_at',
        ),
        migrations.AddField(
            model_name='game',
            name='is_cart',
            field=models.BooleanField(default=False),
        ),
    ]
